import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/Components/Headers/NavBar";
import { Footer } from "@/Components/Footer/Footer";

const inter = Poppins({
  style: ["normal", "italic"],
  weight: ["400", "700", "500", "800"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />

        {children}
        <Footer />
      </body>
    </html>
  );
}
